
// Objective-C API for talking to the following Go packages
//
//	github.com/sonr-io/core/cmd/lib
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Core_FRAMEWORK_H__
#define __Core_FRAMEWORK_H__

#include "Lib.objc.h"
#include "Universe.objc.h"

#endif
