// Objective-C API for talking to github.com/sonr-io/core/cmd/lib Go package.
//   gobind -lang=objc github.com/sonr-io/core/cmd/lib
//
// File is generated by gobind. Do not edit.

#ifndef __Lib_H__
#define __Lib_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


@class LibSonrLib;

@interface LibSonrLib : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@end

/**
 * Pause pauses the host, node, and rpc service.
 */
FOUNDATION_EXPORT void LibPause(void);

/**
 * Resume resumes the host, node, and rpc service.
 */
FOUNDATION_EXPORT void LibResume(void);

/**
 * Start starts the host, node, and rpc service.
 */
FOUNDATION_EXPORT NSData* _Nullable LibStart(NSData* _Nullable reqBytes);

/**
 * Stop closes the host, node, and rpc service.
 */
FOUNDATION_EXPORT void LibStop(void);

#endif
