# ** ================== **
# **    PROJECT INFO    **
# ** ================== **
# -- Basic --
name: sonr_app
description: The dead simple way to connect with people and transfer files.
version: 0.10.0+46
publish_to: none

# -- Flutter Settings --
environment:
  sdk: '>=2.12.0 <3.0.0'

# ** ================== **
# **    DEPENDENCIES    **
# ** ================== **
dependencies:
  # ** --- SDK -- **
  flutter:
    sdk: flutter

  # ** - User Defined - **
  # -- Management --
  bip39: ^1.0.6
  flutter_dotenv: ^5.0.2
  intercom_flutter: ^5.0.2
  intl: ^0.17.0

  # -- Device --
  camerawesome: ^0.3.0+1
  connectivity_plus: ^1.1.0
  package_info: ^2.0.2

  # -- Data --
  photo_manager: ^1.3.1
  share_plus: ^2.1.4
  video_player: ^2.1.14

  # -- Network --
  receive_sharing_intent: ^1.4.5

  # -- Plugins --
  sonr_plugin:
    path: ../

  # -- UI/UX --
  animate_do: ^2.0.0
  flutter_svg: ^0.22.0
  introduction_screen: ^2.1.0
  lottie: ^1.1.0
  pin_code_fields: ^7.3.0
  rive: ^0.7.28
  showcaseview: ^1.1.0
  supercharged: ^2.0.0
  onboarding: ^2.1.0

# ** -- DEV Dependencies -- **
dev_dependencies:
  build_runner: ^2.0.5

flutter_test:
  sdk: flutter

# ** ================== **
# **   FLUTTER BUILD    **
# ** ================== **
flutter:
  uses-material-design: true

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-100.ttf
          weight: 100
        - asset: assets/fonts/Montserrat-100-italic.ttf
          weight: 100
          style: italic
        - asset: assets/fonts/Montserrat-300.ttf
          weight: 300
        - asset: assets/fonts/Montserrat-300-italic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Montserrat-400.ttf
          weight: 400
        - asset: assets/fonts/Montserrat-400-italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/Montserrat-500.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-500-italic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Montserrat-700-italic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Montserrat-700.ttf
          weight: 700
        - asset: assets/fonts/Montserrat-700-italic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Montserrat-900.ttf
          weight: 900
        - asset: assets/fonts/Montserrat-900-italic.ttf
          weight: 900
          style: italic

    - family: SonrIcons
      fonts:
        - asset: assets/fonts/Sonricons.ttf

    - family: SonrNavIcons
      fonts:
        - asset: assets/fonts/SonrNavIcons.ttf

  # -- Media --
  assets:
    - assets/animations/
    - assets/fonts/
    - assets/icons/Chart/
    - assets/icons/Communication/
    - assets/icons/DateTime/
    - assets/icons/Design/
    - assets/icons/Device/
    - assets/icons/FileSystem/
    - assets/icons/Finance/
    - assets/icons/Food/
    - assets/icons/Formatting/
    - assets/icons/MediaControl/
    - assets/icons/Medical/
    - assets/icons/Navigation/
    - assets/icons/SelfCare/
    - assets/icons/Shopping/
    - assets/icons/SocialMedia/
    - assets/icons/Sports/
    - assets/icons/UI/
    - assets/images/illustrations/
    - assets/images/svg/
    - assets/images/utility/
    - assets/sounds/
